// Article scope and recipient comparisons are prepared and tested in Python.
const beforeAsylumRender=render;
const euroExact=v=>v===null?'Niet beschikbaar':new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v);
function asylumPosts(rows){return `<div class="wrap"><table><tr><th>Post / begrotingsartikel</th><th>Bedrag</th><th>Bron</th></tr>${rows.map(r=>`<tr><td>${esc(r.regeling)}<div class="mut">${esc(r.hoofdstuk)} · ${esc(r.artikel)} · ${esc(r.ibos)} · regel ${r.bronregel}</div></td><td class="n">${euroExact(r.bedrag)}</td><td>${sourceLink(r)}</td></tr>`).join('')}</table></div>`}
function vAsylum(){const a=D.asiel[S.y];if(!a||a.status!=='beschikbaar')return '<div class="card">De afbakening voor dit jaar is nog niet gevalideerd.</div>';
 const rows=a.groepen.flatMap(g=>g.posten.map(r=>[g.naam,r.regeling,r.hoofdstukcode,r.artikelcode,r.ibos,r.bedrag,r.bron,r.bronregel]));
 csv('asiel_migratie_artikel37_'+S.y,[['Groep','Post','Hoofdstuk','Artikel','IBOS','Bedrag EUR','Bron','Bronregel'],...rows]);
 return `<div class="card"><h2>Asiel en migratie · ${S.y}</h2><p>Van begrotingsartikel naar organisatie. Dit overzicht volgt artikel 37 (${esc(a.hoofdstuk)}) en omvat ook reguliere migratie, terugkeer en opvang van Oekraïense ontheemden. Het is <b>geen totaal van uitsluitend asielkosten</b>.</p><p>IND behandelt ook reguliere verblijfsaanvragen en naturalisatie. Ook het gehele IND-bedrag is daarom geen asielbedrag. Gemeentelijke uitgaven, rechtsbijstand en andere begrotingsartikelen zijn niet volledig meegenomen.</p><p><a href="${esc(a.toelichting)}" target="_blank" rel="noopener">Beleidstoelichting ${S.y}${D.jaren[S.y].soort==='raming'?' (oorspronkelijke begroting; bedragen hieronder volgen de actuele fase)':''}</a></p><div class="kpis"><div class="kpi">Artikel 37 · ${esc(D.jaren[S.y].soort)}<b>${euroExact(a.artikel.bedrag)}</b></div><div class="kpi">Artikeltotaal minus detailposten<b>${euroExact(a.aansluitverschil)}</b></div></div><p>De groepen hieronder verdelen de detailposten; tel ze niet nog eens bij het artikeltotaal op. Een aansluitverschil blijft zichtbaar.</p><button class="btn" data-a="csv">Download alle artikelposten</button></div>`+
 `<div class="card"><h2>Waar gaat artikel 37 naartoe?</h2>${a.groepen.map(g=>`<details><summary><b>${esc(g.naam)}</b> · ${euroExact(g.bedrag)} · ${g.posten.length} posten</summary>${asylumPosts(g.posten)}</details>`).join('')}</div>`+
 `<div class="card"><h2>Sluiten de organisatiebedragen aan?</h2><p>Hier vergelijken we alle exact herkende Rijksbegrotingsposten voor deze organisaties, dus ook buiten artikel 37, met de afzonderlijke ontvangersbron. Het verschil is ontvangersbron minus begrotingsposten; alleen berekend bij twee beschikbare realisaties van hetzelfde jaar. Een gelijk bedrag bewijst geen transactiekoppeling. Een verschil is geen bewijs van extra of verdwenen geld.</p><p>${esc(D.ontvangerdekking[S.y])}</p>${a.ontvangerbron?`<p><a href="${esc(a.ontvangerbron)}" target="_blank" rel="noopener">Ontvangersbron ${S.y}</a></p>`:''}</div>`+
 a.organisaties.map(o=>`<div class="card"><h2>${esc(o.naam)}</h2><div class="kpis"><div class="kpi">Benoemde Rijksbegrotingsposten<b>${euroExact(o.begrotingsbedrag)}</b></div><div class="kpi">Ontvangersbron · realisatie<b>${euroExact(o.ontvangerbedrag)}</b></div><div class="kpi">Verschil tussen bronbeelden<b>${euroExact(o.verschil)}</b></div></div><p>${o.verschil===null?'Geen vergelijkbaar verschil: één bron ontbreekt of het begrotingsbedrag is een raming.':o.verschil===0?'De bedragen sluiten numeriek aan. De bestemming binnen de organisatie is hiermee niet aangetoond.':'Het verschil is nog niet verklaard. Controleer de bronafbakening, subsidievaststellingen en afrekeningen voordat conclusies worden getrokken.'}</p><details><summary>Alle benoemde begrotingsposten (${o.begrotingsposten.length})</summary>${asylumPosts(o.begrotingsposten)}</details><details><summary>Daarvan buiten artikel 37 (${o.buiten_artikel.length})</summary>${asylumPosts(o.buiten_artikel)}</details><h3>Gepubliceerde ontvangersnamen</h3>${o.ontvangerregels.length?o.ontvangerregels.map(r=>`<p>${esc(r.naam)}: ${euroExact(r.bedrag)}</p>`).join(''):'<p>Geen exact gekoppelde ontvangergegevens. Ontbrekend betekent niet nul.</p>'}</div>`).join('')+
 `<div class="card"><h2>Wat is nog niet bewezen?</h2><p>De koppeling gebruikt een expliciete namenlijst, geen KvK- of betalingsidentificatie. Doorbetalingen door COA en andere uitvoerders aan leveranciers zijn nog niet gevolgd. ODA-toerekening en organisatiesubsidies mogen niet als extra uitgaven bovenop deze bijdragen worden opgeteld. Ontvangsten/terugbetalingen worden hier niet automatisch verrekend.</p></div>`;
}
TABS.splice(1,0,['asiel','Asiel & migratie']);
render=function(){beforeAsylumRender();if(S.q.length<2&&!S.m&&S.t==='asiel')$('#view').innerHTML=vAsylum()};
render();
